# Generated by Django 6.0.4 on 2026-05-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhooks_we_endpoin_07f4b5_idx',
            old_name='webhooks_we_endpoin_idx',
        ),
    ]
