# Generated by Django 6.0.4 on 2026-05-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_rename_webhooks_we_endpoin_idx_webhooks_we_endpoin_07f4b5_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='sheet_tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
