# Generated by Django 6.0.4 on 2026-05-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_webhookevent_sheet_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='mailchimp_tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
