# Generated by Django 5.2.17 on 2026-09-24 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_webhookevent_mailchimp_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('tag', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-event_date', 'city'],
                'indexes': [models.Index(fields=['city', 'event_date'], name='webhooks_ev_city_656e93_idx')],
            },
        ),
    ]
