# Generated by Django 5.2.17 on 2026-08-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_webhookevent_mailchimp_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='forward_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='forward_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='forward_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
