# Generated by Django 5.2.16 on 2026-07-11 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Blog / news index URL to crawl for content.')),
                ('is_active', models.BooleanField(default=True)),
                ('crawl_limit', models.PositiveIntegerField(default=25, help_text='Maximum pages Firecrawl will fetch per refresh.')),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='competitors.competitorsource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='competitors_source__5123b8_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'url'), name='unique_source_url')],
            },
        ),
    ]
