# Generated by Django 5.2.16 on 2026-07-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorcontentitem',
            name='platform',
            field=models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='competitorsource',
            name='instagram_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='competitorsource',
            name='tiktok_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='competitorsource',
            name='youtube_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='competitorsource',
            name='crawl_limit',
            field=models.PositiveIntegerField(default=25, help_text='Maximum pages Firecrawl will fetch per website crawl.'),
        ),
        migrations.AlterField(
            model_name='competitorsource',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Website / blog index URL to crawl.', max_length=500),
        ),
    ]
