# Generated by Django 5.2.16 on 2026-07-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_competitorcontentitem_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsource',
            name='last_refresh_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='competitorsource',
            name='last_refresh_status',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='competitorsource',
            name='refresh_requested',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='competitorsource',
            name='crawl_limit',
            field=models.PositiveIntegerField(default=25, help_text='Maximum posts/pages to fetch per channel each refresh.'),
        ),
    ]
