# Generated by Django 5.2.16 on 2026-07-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0003_competitorsource_last_refresh_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorcontentitem',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
