# Generated by Django 5.2.16 on 2026-07-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0004_competitorcontentitem_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorsource',
            name='crawl_limit',
            field=models.PositiveIntegerField(default=50, help_text='Max items to fetch per channel each refresh (website pages, Instagram/TikTok posts, YouTube videos).'),
        ),
    ]
