# Generated by Django 5.2.16 on 2026-07-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0005_alter_competitorsource_crawl_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsource',
            name='backfill_requested',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='competitorsource',
            name='crawl_limit',
            field=models.PositiveIntegerField(default=25, help_text='Max items per channel on each recurring refresh (website pages, Instagram/TikTok posts, YouTube videos). The first refresh pulls deeper (see COMPETITOR_BACKFILL_LIMIT).'),
        ),
    ]
