# Generated by Django 5.2.16 on 2026-07-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0006_competitorsource_backfill_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorsource',
            name='url',
        ),
        migrations.AlterField(
            model_name='competitorsource',
            name='crawl_limit',
            field=models.PositiveIntegerField(default=25, help_text='Max items per channel on each recurring refresh (Instagram/TikTok posts, YouTube videos). The first refresh pulls deeper (see COMPETITOR_BACKFILL_LIMIT).'),
        ),
    ]
