# Generated by Django 5.2.16 on 2026-07-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0007_remove_competitorsource_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsource',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='competitorsource',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
