# Generated by Django 5.2.16 on 2026-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0008_competitorsource_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorsource',
            name='is_own_brand',
            field=models.BooleanField(default=False, help_text='Track this as one of your own brand accounts (analyzed alongside competitors).'),
        ),
    ]
