# Generated by Django 5.2.16 on 2026-07-12 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0009_competitorsource_is_own_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandscapeReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('markdown', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
