# Generated by Django 5.2.16 on 2026-07-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0010_landscapereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscapereport',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landscapereport',
            name='generation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landscapereport',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landscapereport',
            name='status',
            field=models.CharField(default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='landscapereport',
            name='markdown',
            field=models.TextField(blank=True, default=''),
        ),
    ]
