# Generated by Django 5.2.16 on 2026-07-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0012_competitorsource_youtube_uploads_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscapereport',
            name='trigger',
            field=models.CharField(default='manual', max_length=20),
        ),
    ]
